import { db } from './index';
import { v4 as uuid } from 'uuid';
import type { Material, Sentence } from '@/models';

const now = Date.now();

const seedMaterials: Material[] = [
  {
    id: uuid(),
    title: 'Ordering Coffee',
    description: 'A typical conversation at a coffee shop. Learn how to order drinks and interact with baristas.',
    language: 'en',
    level: 'A1',
    topic: 'daily-conversation',
    type: 'dialogue',
    duration: 45,
    sentenceCount: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Job Interview',
    description: 'Common questions and answers in a job interview setting. Practice professional English.',
    language: 'en',
    level: 'B1',
    topic: 'business',
    type: 'dialogue',
    duration: 120,
    sentenceCount: 12,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Checking into a Hotel',
    description: 'Learn the essential phrases for checking into a hotel, asking about amenities, and handling common requests.',
    language: 'en',
    level: 'A2',
    topic: 'travel',
    type: 'conversation',
    duration: 60,
    sentenceCount: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Small Talk at a Party',
    description: 'Practice casual conversation starters and responses for social gatherings.',
    language: 'en',
    level: 'A2',
    topic: 'daily-conversation',
    type: 'conversation',
    duration: 50,
    sentenceCount: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'TED Talk: The Power of Yet',
    description: 'Excerpt from a motivational speech about growth mindset. Practice speech-style delivery.',
    language: 'en',
    level: 'B2',
    topic: 'education',
    type: 'speech',
    duration: 90,
    sentenceCount: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'At the Doctor\'s Office',
    description: 'Describing symptoms and understanding medical advice in English.',
    language: 'en',
    level: 'B1',
    topic: 'health',
    type: 'dialogue',
    duration: 70,
    sentenceCount: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Making Restaurant Reservations',
    description: 'Learn how to book a table, ask about the menu, and handle dietary requirements.',
    language: 'en',
    level: 'A2',
    topic: 'food',
    type: 'conversation',
    duration: 40,
    sentenceCount: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Tech Support Call',
    description: 'A conversation with tech support about a computer issue. Practice technical vocabulary.',
    language: 'en',
    level: 'B2',
    topic: 'technology',
    type: 'dialogue',
    duration: 80,
    sentenceCount: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Asking for Directions',
    description: 'Navigate through a city by asking for and understanding directions.',
    language: 'en',
    level: 'A1',
    topic: 'travel',
    type: 'conversation',
    duration: 35,
    sentenceCount: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuid(),
    title: 'Presentation: Climate Change',
    description: 'A short presentation on climate change basics. Practice formal presentation delivery.',
    language: 'en',
    level: 'C1',
    topic: 'nature',
    type: 'speech',
    duration: 100,
    sentenceCount: 10,
    createdAt: now,
    updatedAt: now,
  },
];

const sentenceData: Record<number, { text: string; translation: string }[]> = {
  0: [ // Ordering Coffee
    { text: 'Hi there! What can I get for you today?', translation: '你好！今天想喝点什么？' },
    { text: 'I\'d like a medium latte, please.', translation: '我要一杯中杯拿铁，谢谢。' },
    { text: 'Sure! Would you like that hot or iced?', translation: '好的！要热的还是冰的？' },
    { text: 'Hot, please. And could I get an extra shot of espresso?', translation: '热的，谢谢。可以多加一份浓缩咖啡吗？' },
    { text: 'Of course! That\'ll be an extra fifty cents. Anything else?', translation: '当然可以！多加五十美分。还需要别的吗？' },
    { text: 'No, that\'s all. How much is it?', translation: '不用了，就这些。多少钱？' },
    { text: 'That\'ll be four dollars and seventy-five cents.', translation: '一共四美元七十五美分。' },
    { text: 'Here you go. Thank you!', translation: '给你。谢谢！' },
  ],
  1: [ // Job Interview
    { text: 'Thank you for coming in today. Could you tell me a bit about yourself?', translation: '感谢你今天来面试。能简单介绍一下自己吗？' },
    { text: 'Of course. I\'ve been working in marketing for about five years now.', translation: '当然。我在市场营销领域工作了大约五年。' },
    { text: 'What would you say is your greatest strength?', translation: '你认为��最大的优势是什么？' },
    { text: 'I\'d say my ability to adapt quickly to new situations.', translation: '我觉得是我能快速适应新环境的能力。' },
    { text: 'That\'s great. And what about your weaknesses?', translation: '很好。那你的弱点呢？' },
    { text: 'I sometimes take on too many projects at once, but I\'ve been working on prioritizing better.', translation: '我有时会同时承担太多项目，但我一直在努力提高优先级管理。' },
    { text: 'Where do you see yourself in five years?', translation: '五年后你觉得自己会在哪里？' },
    { text: 'I hope to be leading a team and contributing to the company\'s strategic growth.', translation: '我希望能够领导一个团队，为公司的战略发展做出贡献。' },
    { text: 'Do you have any questions for us about the role?', translation: '关于这个职位，你有什么问题想问我们吗？' },
    { text: 'Yes, I\'d love to know more about the team culture and day-to-day responsibilities.', translation: '有的，我想多了解一些团队文化和平日的具体职责。' },
    { text: 'We have a very collaborative environment. Everyone supports each other.', translation: '我们的环境非常注重协作，大家都互相支持。' },
    { text: 'That sounds exactly like the kind of place I\'d love to work. Thank you for your time.', translation: '这正是我想要工作的地方。感谢您的时间。' },
  ],
  2: [ // Checking into a Hotel
    { text: 'Good evening. Do you have a reservation?', translation: '晚上好。您有预订吗？' },
    { text: 'Yes, I have a reservation under the name Chen.', translation: '有的，我用陈这个名字预订了。' },
    { text: 'Let me look that up. Yes, here it is. A single room for three nights.', translation: '让我查一下。是的，找到了。一间单人房，住三晚。' },
    { text: 'That\'s right. Is breakfast included?', translation: '没错。含早餐吗？' },
    { text: 'Yes, breakfast is served from seven to ten in the morning.', translation: '是的，早餐供应时间是早上七点到十点。' },
    { text: 'Great. What time is check-out?', translation: '太好了。退房时间是几点？' },
    { text: 'Check-out is at eleven AM. Here\'s your key card. You\'re in room 512.', translation: '退房时间是上午十一点。这是您的房卡，您在512房间。' },
    { text: 'Thank you. Is there a gym in the hotel?', translation: '谢谢。酒店有健身房吗？' },
    { text: 'Yes, it\'s on the second floor and open 24 hours.', translation: '有的，在二楼，24小时开放。' },
    { text: 'Perfect. I appreciate your help!', translation: '太好了。感谢你的帮助！' },
  ],
  3: [ // Small Talk at a Party
    { text: 'Hi, I don\'t think we\'ve met. I\'m Sarah.', translation: '嗨，我们好像没见过。我是Sarah。' },
    { text: 'Nice to meet you, Sarah. I\'m David. How do you know the host?', translation: '很高兴认识你，Sarah。我是David。你怎么认识主人的？' },
    { text: 'We went to college together. What about you?', translation: '我们是大学同学。你呢？' },
    { text: 'We work at the same company. So what do you do?', translation: '我们在同一家公司工作。你是做什么的？' },
    { text: 'I\'m a graphic designer. I work for a small design studio downtown.', translation: '我是一名平面设计师，在市中心一家小设计工作室工作。' },
    { text: 'That sounds really interesting! What kind of projects do you work on?', translation: '听起来很有趣！你都做什么类型的项目？' },
    { text: 'Mostly branding and web design. I really enjoy the creative process.', translation: '主要是品牌设计和网页设计。我真的很享受创作过程。' },
    { text: 'I\'d love to see some of your work sometime.', translation: '有机会真想看看你的作品。' },
  ],
  4: [ // TED Talk: The Power of Yet
    { text: 'The power of yet is a simple concept that can transform how we learn.', translation: '"还没有"的力量是一个可以改变我们学习方式的简单概念。' },
    { text: 'When students fail a test, instead of saying they failed, we can say they haven\'t succeeded yet.', translation: '当学生考试不及格时，与其说他们失败了，不如说他们还没有成功。' },
    { text: 'This small shift in language creates a growth mindset in learners.', translation: '这种语言上的微小转变在学习者心中创造了成长型思维。' },
    { text: 'Students with a growth mindset understand that their abilities can be developed.', translation: '拥有成长型思维的学生明白，他们的能力是可以培养的。' },
    { text: 'They embrace challenges instead of running away from them.', translation: '他们拥抱挑战，而不是逃避挑战。' },
    { text: 'They see effort as the path to mastery, not as something to be ashamed of.', translation: '他们把努力看作通往精通的途径，而不是值得羞愧的事情。' },
    { text: 'The brain is like a muscle — the more you use it, the stronger it gets.', translation: '大脑就像肌肉——用得越多，它就越强壮。' },
    { text: 'When you make a mistake, your brain grows new connections.', translation: '当你犯错时，你的大脑会建立新的连接。' },
    { text: 'So the next time you face a difficult problem, remember: you just haven\'t figured it out yet.', translation: '所以下次面对难题时，记住：你只是还没有找到解决方法而已。' },
    { text: 'With the power of yet, every challenge becomes an opportunity to grow.', translation: '有了"还没有"的力量，每一个挑战都变成了成长的机会。' },
  ],
  5: [ // At the Doctor's Office
    { text: 'Good morning, Doctor. I\'ve been feeling unwell for the past few days.', translation: '早上好，医生。我最近几天一直感觉不舒服。' },
    { text: 'I see. Can you describe your symptoms?', translation: '我明白了。你能描述一下你的症状吗？' },
    { text: 'I have a persistent cough and a slight fever. I also feel very tired.', translation: '我一直咳嗽，还有点发烧。我也觉得很累。' },
    { text: 'How long have you had these symptoms?', translation: '这些症状持续多久了？' },
    { text: 'About three days now. It started with a sore throat.', translation: '大约三天了。一开始是喉咙痛。' },
    { text: 'Let me check your temperature and listen to your breathing.', translation: '让我量一下你的体温，听听你的呼吸。' },
    { text: 'Your temperature is 38.2 degrees. I can hear some congestion in your lungs.', translation: '你的体温是38.2度。我能听到肺部有些充血。' },
    { text: 'Is it serious?', translation: '严重吗？' },
    { text: 'It looks like a respiratory infection. I\'ll prescribe some antibiotics.', translation: '看起来是呼吸道感染。我给你开一些抗生素。' },
    { text: 'Thank you, Doctor. How often should I take the medicine?', translation: '谢谢医生。药该怎么吃？' },
  ],
  6: [ // Making Restaurant Reservations
    { text: 'Good evening, this is La Maison. How can I help you?', translation: '晚上好，这里是La Maison餐厅。有什么可以帮您的？' },
    { text: 'Hi, I\'d like to make a reservation for this Friday evening.', translation: '你好，我想预订这个周五晚上的位置。' },
    { text: 'Certainly. For how many people and what time?', translation: '好的。几位？几点？' },
    { text: 'For four people at seven thirty, please.', translation: '四位，七点半，谢谢。' },
    { text: 'Let me check. Yes, we have a table available at seven thirty.', translation: '让我查一下。是的，七点半有位置。' },
    { text: 'Great. Also, one of my friends is vegetarian. Do you have vegetarian options?', translation: '太好了。对了，我有个朋友是素食主义者，你们有素食选择吗？' },
    { text: 'Absolutely. We have a full vegetarian menu. I\'ll make a note on your reservation.', translation: '当然有。我们有完整的素食菜单。我会在您的预订上注明。' },
    { text: 'Perfect. The reservation is under the name Wang.', translation: '太好了。预订名字是王。' },
  ],
  7: [ // Tech Support Call
    { text: 'Thank you for calling TechSupport. This is Alex speaking. How can I help?', translation: '感谢致电技术支持。我是Alex，有什么可以帮您的？' },
    { text: 'Hi Alex. My laptop keeps freezing whenever I open multiple applications.', translation: '你好Alex。我的笔记本电脑一打开多个应用就死机。' },
    { text: 'I see. When did this problem first start happening?', translation: '明白了。这个问题是什么时候开始出现的？' },
    { text: 'It started about two days ago, right after a system update.', translation: '大约两天前，就在系统更新之后。' },
    { text: 'That could be related. Can you tell me which operating system you\'re running?', translation: '这可能有关联。能告诉我你用的是哪个操作系统吗？' },
    { text: 'I\'m on Windows 11. The update was a security patch.', translation: '我用的是Windows 11。更新的是一个安全补丁。' },
    { text: 'Okay, let\'s try a few troubleshooting steps. First, have you tried restarting?', translation: '好的，我们来试试几个排查步骤。首先，你试过重启吗？' },
    { text: 'Yes, several times. It helps temporarily but the problem comes back.', translation: '试过好几次了。能暂时缓解，但问题又会复发。' },
    { text: 'Let\'s check your task manager to see if any processes are using too much memory.', translation: '我们来看看任务管理器，看有没有进程占用太多内存。' },
    { text: 'I can see that my browser is using a lot of RAM, but I need it for work.', translation: '我看到浏览器占用了很多内存，但我工作需要用到它。' },
  ],
  8: [ // Asking for Directions
    { text: 'Excuse me, could you tell me how to get to the train station?', translation: '打扰一下，能告诉我去火车站怎么走吗？' },
    { text: 'Sure! Go straight down this street for about two blocks.', translation: '当然！沿着这条街直走大约两个街区。' },
    { text: 'Okay, two blocks. Then what?', translation: '好的，两个街区。然后呢？' },
    { text: 'Then turn right at the traffic light. You\'ll see a big supermarket on the corner.', translation: '然后在红绿灯处右转。你会看到拐角处有一个大超市。' },
    { text: 'I see. Is the station near the supermarket?', translation: '明白了。车站在超市附近吗？' },
    { text: 'Yes, it\'s right across the street from the supermarket. You can\'t miss it.', translation: '是的，就在超市马路对面。不会错过的。' },
    { text: 'About how long does it take to walk there?', translation: '走过去大概要多久？' },
    { text: 'It takes about ten minutes on foot.', translation: '步行大约十分钟。' },
  ],
  9: [ // Presentation: Climate Change
    { text: 'Good morning, everyone. Today I\'d like to talk about climate change and its impact on our planet.', translation: '大家早上好。今天我想谈谈气候变化及其对我们星球的影响。' },
    { text: 'Over the past century, the Earth\'s average temperature has risen by approximately 1.1 degrees Celsius.', translation: '在过去的一个世纪里，地球的平均温度上升了大约1.1摄氏度。' },
    { text: 'This may not sound like much, but it has profound effects on our ecosystems.', translation: '这听起来可能不多，但对我们的生态系统产生了深远的影响。' },
    { text: 'We are seeing more frequent extreme weather events, from hurricanes to wildfires.', translation: '我们看到越来越多的极端天气事件，从飓风到野火。' },
    { text: 'Sea levels are rising at an accelerating rate, threatening coastal communities worldwide.', translation: '海平面正在加速上升，威胁着全世界的沿海社区。' },
    { text: 'The primary cause is the emission of greenhouse gases from human activities.', translation: '主要原因是人类活动排放的温室气体。' },
    { text: 'However, there is still hope. Renewable energy technology is advancing rapidly.', translation: '然而，仍然有希望。可再生能源技术正在快速发展。' },
    { text: 'Solar and wind power are now cheaper than fossil fuels in many parts of the world.', translation: '在世界许多地方，太阳能和风能现在比化石燃料更便宜。' },
    { text: 'Each of us can make a difference through small daily choices.', translation: '我们每个人都可以通过日常的小选择来做出改变。' },
    { text: 'Together, we can build a sustainable future for generations to come. Thank you.', translation: '我们一起，可以为子孙后代建设一个可持续的未来。谢谢。' },
  ],
};

export async function seedDatabase(): Promise<void> {
  const count = await db.materials.count();
  if (count > 0) return; // Already seeded

  for (let i = 0; i < seedMaterials.length; i++) {
    const material = seedMaterials[i];
    const sentences = sentenceData[i];

    if (!sentences) continue;

    const durationPerSentence = material.duration / sentences.length;

    const sentenceRecords: Sentence[] = sentences.map((s, idx) => ({
      id: uuid(),
      materialId: material.id,
      order: idx,
      text: s.text,
      translation: s.translation,
      startTime: idx * durationPerSentence,
      endTime: (idx + 1) * durationPerSentence,
      duration: durationPerSentence,
      language: 'en' as const,
    }));

    await db.materials.put(material);
    await db.sentences.bulkPut(sentenceRecords);
  }

  // Seed default settings
  await db.settings.put({
    id: 1,
    nativeLanguage: 'zh-CN',
    learningLanguages: ['en', 'yue', 'ja', 'ko', 'fr'],
    primaryLanguage: 'en',
    speechRate: 0.9,
    dailyWordGoal: 20,
    dailySentenceGoal: 10,
    dailySpeakingGoal: 5,
    dailyListeningGoal: 3,
    theme: 'system',
  });
}
